### ISSUE TITLE
How to use combojack?

### ISSUE THREAD

**Issue by sleepsz** [itsabhishekolkha/Mi-notebook-14-Hackintosh#10]
Followed the guide of combojack and it didn't boot

**Comment by itsabhishekolkha** [comment]
sorry for the late reply bro, yes, it's will not boot after installing `combojack`  because you need to make some changes in `config.plist`. here are the steps you need to perform...
1.download `combojack` for the link provided on GitHub.
2.mount your hard drive `EFI` and go to EFI->OC->Kext-> and delete `CodecCommander.kext`
3. Put `verbstub.kext` in kext folder.
4. now you need to make changes in config .plist...
5. remove `codeccommander` kext entry from `Config.plist` and add `VerbStub.kext` entry and then **Save it.**
6. **REBOOT** and you are good to go.
7. *NOTE*:- if you arn't well aware about how to make changes in `config.plist`, i can do that for you.

**Comment by TonyPSR** [comment]
This issue can be closed IMO.

**Comment by sleepsz** [comment]
> This issue can be closed IMO.

Sorry I didn't checked it, hence forgotten

**Comment by sleepsz** [comment]
> sorry for the delayed reply bro, yes, it's will not boot after installing `combojack` because you need to make some changes in `config.plist`. here are the steps you need to perform...
> 1.download `combojack` for the link provided on GitHub.
> 2.mount your hard drive `EFI` and go to EFI->OC->Kext-> and delete `CodecCommander.kext`
> 3. Put `verbstub.kext` in kext folder.
> 4. now you need to make changes in config .plist...
> 5. remove `codeccommander` kext entry from `Config.plist` and add `VerbStub.kext` entry and then **Save it.**
> 6. **REBOOT** and you are good to go.
> 7. _NOTE_:- if you arn't well aware about how to make changes in `config.plist`, i can do that for you.

Okay trying now
