### ISSUE TITLE
Sleep not working on Horizon

### ISSUE THREAD

**Issue by PhantomZNeuroX** [itsabhishekolkha/Mi-notebook-14-Hackintosh#11]
Sleep is not working, Horizon I5 

Putting the laptop manually to sleep via the menu with nothing connected to the USB ports
I have made my own EFI but sleep isn't working in it and seeing that your EFI fixed sleep, I was motivated to shift to yours, Could you tell me what did you do in your EFI to fix sleep?

 - OS: [Big Sur11.4]
 - Device: Mi notebook 14 Horizon I5
 
Thanks :)

**Comment by itsabhishekolkha** [comment]
I'll surely help you... but may I have a look at your *EFI* bro?
just upload it on any drive and share the link with me. And then I'll explain to you what's wrong with your *EFI*

**Comment by chadify** [comment]
> I'll surely help you... but may I have a look at your _EFI_ bro?
> just upload it on any drive and share the link with me. And then I'll explain to you what's wrong with your _EFI_

Thanks for swift reply. Me and @PhantomZNeuroX have built EFI from scratch, everything works except sleep. I've made [this reddit post](https://www.reddit.com/r/hackintosh/comments/owo9v5/helpsleep_issues_with_my_hack_in_my_laptop/h7lkje1/?context=3) regarding this issue, EFI and sleep log are attached with this post.

Also, can you join us on [Xiaomi Mi Notebook Hackintosh Discord Server](https://discord.gg/usyMBhhd)? As there are more people there having same issues and It'll be easy to interact and guide.

**Comment by PhantomZNeuroX** [comment]
> I'll surely help you... but may I have a look at your _EFI_ bro?
> just upload it on any drive and share the link with me. And then I'll explain to you what's wrong with your _EFI_

Here is the EFI,

 https://drive.google.com/file/d/1awpyBDU5unn5z2-DWPNUqeN-tsWujndv/view?usp=sharing

**Comment by itsabhishekolkha** [comment]
> > I'll surely help you... but may I have a look at your _EFI_ bro?
> > just upload it on any drive and share the link with me. And then I'll explain to you what's wrong with your _EFI_
> 
> Thanks for the swift reply. Me and @PhantomZNeuroX have built EFI from scratch, everything works except sleep. I've also made [this reddit post](https://www.reddit.com/r/hackintosh/comments/owo9v5/helpsleep_issues_with_my_hack_in_my_laptop/h7lkje1/?context=3) regarding this issue, EFI and sleep log are attached with this post.
> 
> Also, can you join us on [Xiaomi Mi Notebook Hackintosh Discord Server](https://discord.gg/usyMBhhd)? As there are more people there having same issues and It'll be easy to interact and guide.

As i can see your *Reddit* post in which you mentioned you used the *EFI* of **uttusharma's** and he told you that the sleep is working in his laptop....that's not possible man because uttusharma is using my `EFI OC 0.7.0` **release clone** you can check his `GitHub repo.` and i fixed the sleep issue in `OC 0.7.1 release.` i don't know why he told you that but till my `OC 0.7.1 release` sleep feature were not working properly.

before the release of `EFI OC 0.7.1` my hackintosh were not sleeping properly. as you mentioned on reddit... *"Sleep is not working. When entering sleep, the display turns off for 30-40 seconds and then turns on to the login page"*, i was facing the same problem.

**Comment by itsabhishekolkha** [comment]
> > I'll surely help you... but may I have a look at your _EFI_ bro?
> > just upload it on any drive and share the link with me. And then I'll explain to you what's wrong with your _EFI_
> 
> Here is the EFI,
> 
> https://drive.google.com/file/d/1awpyBDU5unn5z2-DWPNUqeN-tsWujndv/view?usp=sharing

I'll check your `EFI` and will let you guys. and keep support *mi notebook Hackintosh community*. peace out.

**Comment by itsabhishekolkha** [comment]
As I can see in your `EFI` there are many changes you need to make for proper power management and sleep...

1.*ACPI* --You need some **SSDT'S**
(a) `SSDT ALS0`-> Fake ambient light sensor device.
(b) Use `SSDT AWAC DISABLE`-> Fixing system clocks.
(c)SSDT-DMAC-> This SSDT adds a DMA Controller to the LPCB (Low Pin Count Bus).(not that necessary.)
(d)Use SSDT-EC-USBX-LAPTOP instead of SSDT-EC-USBX. -> For fixing embedded controler.
(e) use SSDT EC-> if you are using BigSur, it's for Catalina users.( but you can keep both.)
(f) SSDT GPI0-> Fixing trackpads.
(g)SSDT LGPA-> for native brightness Hotkeys.
(h)SSDT MCHC-> https://dortania.github.io/Getting-Started-With-ACPI/Universal/smbus.html
(i)SSDT MEM2->Add missing MEM2 Device to enhance performance like a real Mac.
(J)SSDT PMC-> FIXING NVRAM
(K)SSDT RHUB->Fixing USB
(L) SSDT RMNE-> add NullEthernetForce.kext to allow installation without ACPI or PCI …
etc.

2.*KEXT*
 (a) CpuFriendDataProvider-whose kext is this or did you genereted it by yourself??-> this provides native cpu power management and Processor *TurboBoost* .
(b)use airportitwm.kext insted of itwm.kext-> i think you are using Heliport app.
(c) NoTouchID-> in order to save power. and stop system to preventing sleep.
(d)NullEthernet-> save power and stop system from causig any issues of sleep.(we need this in order to get imessage work).
(e)SATAunsupported.kext-> use this kext

3.`config.plist`

(a) DeviceProperties->  you arn't using any deviceproperties except graphics and sound (Device configuration is provided to macOS with a dedicated buffer, called EfiDevicePathPropertyDatabase. This buffer is a serialised map of DevicePaths to a map of property names and their values.)
 use my DeviceProperties.
(b)in kernel->quirks->AppleCpuPmCfgLock-> yes

**Comment by chadify** [comment]
> As I can see in your `EFI` there are many changes you need to make for proper power management and sleep...
> 
> 1._ACPI_ --You need some **SSDT'S**
> (a) `SSDT ALS0`-> Fake ambient light sensor device.
> (b) Use `SSDT AWAC DISABLE`-> Fixing system clocks.
> (c)`SSDT-DMAC`-> This SSDT adds a DMA Controller to the LPCB (Low Pin Count Bus).(not that necessary.)
> (d)Use `SSDT-EC-USBX-LAPTOP` instead of `SSDT-EC-USBX`. -> For fixing embedded controler.
> (e) use SSDT EC``-> if you are using BigSur, it's for Catalina users.( but you can keep both.)
> (f) `SSDT GPI0`-> Fixing trackpads.
> (g)`SSDT LGPA`-> for native brightness Hotkeys.
> (h)`SSDT MCHC`-> https://dortania.github.io/Getting-Started-With-ACPI/Universal/smbus.html
> (i)`SSDT MEM2`->Add missing MEM2 Device to enhance performance like a real Mac.
> (J)`SSDT PMC`-> FIXING NVRAM
> (K)`SSDT RHUB`->Fixing USB
> (L) `SSDT RMNE`-> add NullEthernetForce.kext to allow installation without ACPI or PCI …
> etc.
> 
> 2._KEXT_
> (a) `CpuFriendDataProvider.kext`-whose kext is this or did you genereted it by yourself??-> this provides native cpu power management and Processor _TurboBoost_ .
> (b)use `airportitwm.kext` instead of `itwm.kext` causing any issues of sleep. (we need this in order to get iMessage work).
> (e)`SATAunsupported.kext`-> use this kext
> 
> 3.`config.plist`
> 
> (a) `DeviceProperties`-> you aren't using any `device properties` except graphics and sound (Device configuration is provided to macOS with a dedicated buffer, called EfiDevicePathPropertyDatabase. This buffer is a serialized map of DevicePaths to a map of property names and their values.)
> use my DeviceProperties.
> (b)in kernel->quirks->`AppleCpuPmCfgLock`-> yes

Thanks for taking your time to write this. This helped, I've fixed my sleep and trackpad.

**Comment by chadify** [comment]
@itsabhishekolkha My laptop is i7 Horizon, the device properties of yours and mine should differ, right? If so, can you guide me to custom write my laptop's device properties.

**Comment by itsabhishekolkha** [comment]
sorry for the delayed response. all the properties of yours and mine are the same so you can use my properties. and if you want to generate your own properties you need windows OS.

**Comment by chadify** [comment]
@itsabhishekolkha I’ve messaged you on discord. Please have a look at them.

**Comment by PhantomZNeuroX** [comment]
@itsabhishekolkha Hey, I had a doubt regarding power management, if you don't mind can we talk once?
