### ISSUE TITLE
Too much confusion

### ISSUE THREAD

**Issue by TonyPSR** [itsabhishekolkha/Mi-notebook-14-Hackintosh#6]
Bro, there are too many copies of files. There is a four day old config file in config folder, and  a 4 hours old EFI in the EFI folder. And, the release version still doesn't work. The EFI folder has a OneDrive link that doesn't work. But the change log says that the EFI has been moved directly in the EFI folder.

It would be nice if everything is more streamlined.

One more thing. I guess the USB map is dependent on the macOS 11 version. For me you latest USB Map doesn't work. It would be nice if it's specified the readme file. Like which version you actually tested the EFI on.

Also, it would be nice if you can provide the steps you followed for USB Mapping. I tried USBInjectAll with and without xhci unsupported kext. The hackintool and USBMap program showed no ports. I removed the RHUB SSDT and tried, USB worked but cameras stopped working. 

Keep up with your great work contributing to the Mi Notebook 14 hackintosh community. Once again, thank you for your time and efforts. It would be nice if these issues are fixed.

**Comment by itsabhishekolkha** [comment]
sorry for the inconvenience bro, you were facing the problem because of a wrong **tag.** But now I updated everything as it should be and from now on you don't need to open any link to download **new** **releases,** just download from the release section.

My USB mapping is working for all the Mi NoteBook 14 editions... it's not working in your Hackintosh may be because you made some changes in your `Config.plist` or in any `kexts.` To get your **USB** **mapping** work **remove** your old **EFI** from HDD and replace it with the new one provided in the release section(don't forget to update your old **SMBIOS** to the new `config.plist).`

I will update the USB Mapping guide in the Post-installation section of **README.MD** section ASAP.

And thank you for helping me in improving **Mi NoteBook 14** **Hackintosh** Community.
